version: '3'
services:
  web:
    build: .
    ports:
     - "80:80"
    volumes:
     - .:/var/www/html
    depends_on:
     - db
  db:
    image: "mariadb:10.1.36"
    restart: always
    ports:
     - "3306:3306"
    volumes:
     - mysql_data:/var/lib/mysql
     - ./sql_file:/sql_file
    environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    command:
     "mysqld --innodb-flush-method=fsync"
volumes:
  mysql_data:
